from . import config
import pandas as pd
import time

from pytrends.request import TrendReq

#NOTE: keywords were generated by an LLM
def get_search_data(keywords: dict, save_dir: str):
    '''Gets the search-term data from Google Trends (5-year monthly data, starting from today)'''
    pytrends = TrendReq(hl='en-US', tz=360)
    
    # iterate through the keywords dict, and getting search data trends for each category of keywords
    for category, kws in keywords.items():
        
        print(f"Getting historical search-term data for category: {category}")
        
        pytrends.build_payload(
            kws,
            cat=0,
            geo='PK',  # Pakistan only
            gprop='')
        
        response_df = pytrends.interest_over_time()
        response_df.to_csv(f'{save_dir}/PK_digital_payments_trends_{category}.csv')
        
        time.sleep(2)


if __name__ == "__main__":
    get_search_data(config.PYTRENDS_KEYWORDS, config.SEARCH_TERM_DIR)
