import json

def process_json(raw_json_filepath: str, processed_json_filepath: str):
    '''This function processes the raw JSON object containing the news articles'''
    
    with open(raw_json_filepath, "r") as file:
        data = json.load(file)
        
        
    # viewing the structure of the object
    print(f"Object structure: {list(data.keys())}\n")
    
    # all articles are stored in the array of objects under 'articles'
    raw_article_data = data['articles']
    
    # data of interest: source_name, title, description, content
    
    processed_article_data = []
        
    for article in raw_article_data:
        
        # DISCLAIMER: this parsing logic was generated by an LLM
        processed_article = {
            'source_name': article.get('source', {}).get('name'),
            'title': article.get('title'),
            'description': article.get('description'),
            'content': article.get('content')
        }
        processed_article_data.append(processed_article)
    
    
    # viewing a few processed articles...
    print(f"Viewing a few processed articles...\n")
    for i, article in enumerate(processed_article_data[:3]):
        print(f"Article {i+1}:")
        print(f"Source: {article['source_name']}")
        print(f"Title: {article['title']}")
        print(f"Description: {article['description']}")
        print(f"Content: {article['content']}")
        print("-" * 50)
    
    
    # saving processed articles
    with open(processed_json_filepath, "w") as file:
        json.dump(processed_article_data, file, indent=2)
    